USE [ParkingOnlineDB]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Vaga]') AND type in (N'U'))
DROP TABLE [dbo].[Vaga]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Vaga](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Localizacao] [varchar](3) NOT NULL,
	[Ocupada] [bit] NOT NULL,
 CONSTRAINT [PK_Vaga] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
